import { i18n } from '@/utils/i18n';

const messages = {
  settings: ['设置', 'Settings'],
  subtitle: ['让每一个新标签页，更合你意。', 'Make every new tab feel like yours.'],
  search: ['AI 搜索', 'AI search'],
  bookmarks: ['快捷书签', 'Shortcuts'],
  backgrounds: ['背景', 'Background'],
  anniversaries: ['纪念日', 'Dates'],
  searchIntro: ['选一个默认引擎，让好奇心即刻出发。', 'Choose where your next question takes you.'],
  bookmarksIntro: ['把常用网站放在手边，为不同场景保留两组书签。', 'Keep your everyday destinations close, with two groups for different contexts.'],
  backgroundsIntro: ['每日换一幅风景，或使用你自己的图片与视频。', 'A fresh view each day, or images and videos of your own.'],
  anniversariesIntro: ['留住值得期待的日子，在新标签页轻轻提醒你。', 'Keep the days that matter in sight, right on your new tab.'],
  local: ['仅保存在此浏览器', 'Stored in this browser'],
  localHint: ['无需账号，不上传你的设置。', 'No account. Your settings stay local.'],
  save: ['保存更改', 'Save changes'],
  discard: ['放弃更改', 'Discard changes'],
  dirty: ['有未保存的更改', 'Unsaved changes'],
  clean: ['所有更改已保存', 'All changes saved'],
  saveHint: ['保存后应用到所有新标签页', 'Changes apply to your new tabs when saved'],
  saved: ['更改已保存', 'Changes saved'],
  saveFailed: ['保存失败，更改仍保留在页面中，请重试。', 'Could not save. Your edits are still here; please try again.'],
  restore: ['恢复本分类默认', 'Restore section defaults'],
  restoreGroup: ['恢复当前分组默认', 'Restore group defaults'],
  restoreHint: ['只影响当前分类，保存后生效。', 'Only this section will change, after you save.'],
  restoreGroupHint: ['只恢复当前分组的名称与书签来源。', 'Only this group’s name and bookmark source will change.'],
  confirmTitle: ['恢复默认设置？', 'Restore defaults?'],
  confirmBody: ['将恢复「{name}」的默认配置。其他分类保持不变，你仍需保存才会生效。', 'Restore defaults for “{name}”? Other sections stay as they are. Save to apply the change.'],
  cancel: ['取消', 'Cancel'],
  confirm: ['恢复默认', 'Restore defaults'],
  restored: ['已恢复到默认草稿，保存后生效。', 'Defaults restored to your draft. Save to apply.'],
  defaultProvider: ['默认搜索引擎', 'Default search engine'],
  defaultHint: ['从这里开始搜索；新标签页也会记住你最近使用的引擎。', 'Start here. Your new tab also remembers the engine you used most recently.'],
  engines: ['搜索引擎', 'Search engines'],
  enginesHint: ['按 Alt + ↑ / ↓，在新标签页快速切换。', 'Use Alt + ↑ / ↓ to switch on your new tab.'],
  builtIn: ['内置', 'Built-in'],
  custom: ['自定义', 'Custom'],
  default: ['默认', 'Default'],
  edit: ['编辑', 'Edit'],
  name: ['名称', 'Name'],
  template: ['搜索 URL 模板', 'Search URL template'],
  templateHint: ['用 {query} 代表搜索内容，例如 https://example.com/search?q={query}', 'Use {query} for the search text, e.g. https://example.com/search?q={query}'],
  nameRequired: ['请输入名称。', 'Enter a name.'],
  templateInvalid: ['请输入包含 {query} 的 HTTP 或 HTTPS 搜索链接。', 'Enter an HTTP or HTTPS search URL containing {query}.'],
  urlInvalid: ['请输入有效的 HTTP 或 HTTPS 链接。', 'Enter a valid HTTP or HTTPS URL.'],
  enabled: ['启用此引擎', 'Enable this engine'],
  disabled: ['已停用', 'Disabled'],
  login: ['需要登录', 'Sign-in required'],
  addProvider: ['添加搜索引擎', 'Add search engine'],
  remove: ['删除', 'Remove'],
  groups: ['书签分组', 'Bookmark group'],
  external: ['外网', 'External'],
  internal: ['内网', 'Internal'],
  groupName: ['分组名称', 'Group name'],
  groupHint: ['最多 24 字，留空使用默认名称。', 'Up to 24 characters. Leave blank for the default name.'],
  source: ['书签来源', 'Bookmark source'],
  builtInBookmarks: ['内置书签', 'Built-in bookmarks'],
  builtInHint: ['精选常用网站，开箱即用', 'A ready-to-use collection'],
  json: ['JSON 数据', 'JSON data'],
  jsonHint: ['粘贴或导入你的书签', 'Paste or import your collection'],
  remote: ['远程链接', 'Remote URL'],
  remoteHint: ['从在线 JSON 文件加载', 'Load an online JSON file'],
  bookmarkData: ['书签 JSON', 'Bookmarks JSON'],
  remoteUrl: ['书签 JSON URL', 'Bookmarks JSON URL'],
  remoteHelp: ['链接需允许跨域访问。加载失败时会保留上次有效书签。', 'The URL must allow cross-origin requests. If loading fails, your last valid bookmarks stay available.'],
  validate: ['校验数据', 'Validate data'],
  testUrl: ['测试链接', 'Test URL'],
  testing: ['正在检查…', 'Checking…'],
  refresh: ['刷新已保存的书签', 'Refresh saved bookmarks'],
  refreshHint: ['刷新已保存的来源；不会提交当前草稿。', 'Refreshes the saved source without saving your draft.'],
  valid: ['书签数据有效', 'Bookmark data is valid'],
  preview: ['包含 {count} 个快捷入口', '{count} shortcuts included'],
  backgroundMode: ['当前模式', 'Current mode'],
  daily: ['每日背景', 'Daily background'],
  dailyHint: ['每天自动换一幅风景，无需配置。', 'A fresh image each day. No setup needed.'],
  customBackground: ['自定义背景 · {count} 项', 'Custom backgrounds · {count} items'],
  customBackgroundHint: ['使用新标签页右下角的风车按钮依次切换。', 'Cycle through them with the windmill button on your new tab.'],
  mediaUrls: ['图片与视频链接', 'Image and video URLs'],
  mediaHelp: ['每行一个 HTTP/HTTPS 链接。支持 GIF、APNG、WebP、MP4、WebM、MOV；清空后恢复每日背景。', 'One HTTP/HTTPS URL per line. Supports GIF, APNG, WebP, MP4, WebM and MOV. Clear the list to return to daily backgrounds.'],
  invalidMedia: ['第 {rows} 行链接无效，请使用 HTTP 或 HTTPS。', 'Invalid URLs on lines {rows}. Use HTTP or HTTPS.'],
  image: ['图片', 'Image'],
  video: ['视频', 'Video'],
  noPreview: ['这里只检查链接格式，不会自动下载或播放媒体。', 'URLs are checked locally. Media is not downloaded or played here.'],
  addDate: ['添加纪念日', 'Add a date'],
  emptyDates: ['给下一个期待，留个位置', 'Make room for something to look forward to'],
  emptyDatesHint: ['生日、旅行或一个特别的日子，都可以记在这里。', 'A birthday, a trip, or a day you never want to forget.'],
  date: ['日期', 'Date'],
  dateInvalid: ['请选择有效日期。', 'Choose a valid date.'],
  type: ['类型', 'Type'],
  calendar: ['历法', 'Calendar'],
  note: ['备注（选填）', 'Note (optional)'],
  newDate: ['新的纪念日', 'New date'],
  dateCount: ['{count} 个日子', '{count} dates'],
  unnamed: ['未命名', 'Untitled'],
  invalid: ['请检查标记的字段后再保存。', 'Check the highlighted fields before saving.'],
} as const;

export type CopyKey = keyof typeof messages;
export function s(key: CopyKey, params: Record<string, string | number> = {}) {
  const text = messages[key][i18n.getLanguage() === 'en' ? 1 : 0];
  return text.replace(/\{(\w+)\}/g, (match, name) => name in params ? String(params[name]) : match);
}
